# Generated by Django 4.2.11 on 2024-04-28 19:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Babyreg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Baby_name', models.CharField(blank='False', max_length=30, null='False')),
                ('Baby_number', models.CharField(blank='False', max_length=30, null='False')),
                ('Date', models.DateField(blank='False', max_length=30, null='False')),
                ('Gender', models.CharField(blank='False', max_length=30, null='False')),
                ('Age', models.IntegerField()),
                ('Location', models.CharField(blank='False', max_length=30, null='False')),
                ('Name_of_person_who_brought_the_baby', models.CharField(blank='False', max_length=30, null='False')),
                ('Name_of_the_person_that_has_taken_baby', models.CharField(blank='False', max_length=30, null='False')),
                ('Time_In', models.TimeField(blank='False', max_length=30, null='False')),
                ('Time_Out', models.TimeField(blank='False', max_length=30, null='False')),
                ('Parents_names', models.CharField(blank='False', max_length=30, null='False')),
                ('Comment', models.CharField(blank='False', max_length=100, null='False')),
            ],
        ),
        migrations.CreateModel(
            name='Category_doll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categorystay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_the_doll', models.CharField(blank=True, max_length=200, null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('color', models.CharField(blank=True, max_length=200, null=True)),
                ('size', models.CharField(blank=True, max_length=200, null=True)),
                ('issued_quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('received_quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('Unit_price', models.IntegerField(blank=True, default=0, null=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('c_doll', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.category_doll')),
            ],
        ),
        migrations.CreateModel(
            name='Sitterreg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sitter_name', models.CharField(blank='False', max_length=30, null='False')),
                ('Sitter_number', models.CharField(blank='False', max_length=30, null='False')),
                ('Date_of_birth', models.DateField(blank='True', null='True')),
                ('Contact', models.IntegerField()),
                ('Location', models.CharField(blank='False', max_length=30, null='False')),
                ('Gender', models.CharField(blank='False', max_length=10, null='False')),
                ('Level_of_education', models.CharField(blank='False', max_length=30, null='False')),
                ('Next_of_kin', models.CharField(blank='False', max_length=30, null='False')),
                ('NIN', models.CharField(blank='False', max_length=30, null='False')),
                ('Recommenders_name', models.CharField(blank='False', max_length=30, null='False')),
                ('Religion', models.CharField(blank='True', max_length=30, null='True')),
            ],
        ),
        migrations.CreateModel(
            name='Salesrecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_sold', models.IntegerField(default=0)),
                ('amount_received', models.IntegerField(default=0)),
                ('sale_date', models.DateField(default=django.utils.timezone.now)),
                ('unit_price', models.IntegerField(default=0)),
                ('doll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.doll')),
                ('payee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.babyreg')),
            ],
        ),
        migrations.AddField(
            model_name='babyreg',
            name='assign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.sitterreg'),
        ),
        migrations.AddField(
            model_name='babyreg',
            name='c_stay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.categorystay'),
        ),
    ]
