# Generated by Django 4.2.11 on 2024-05-06 05:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Babyreg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Baby_name', models.CharField(max_length=30)),
                ('Baby_number', models.CharField(max_length=30)),
                ('Date', models.DateField(default=django.utils.timezone.now)),
                ('Gender', models.CharField(max_length=30)),
                ('Age', models.IntegerField()),
                ('Location', models.CharField(max_length=30)),
                ('Parents_names', models.CharField(max_length=30)),
                ('timein', models.TimeField()),
                ('brought', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category_doll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categorystay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_the_doll', models.CharField(blank=True, max_length=200, null=True)),
                ('doll_number', models.CharField(blank=True, max_length=200, null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('issued_quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('received_quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('Unit_price', models.IntegerField(blank=True, default=0, null=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('c_doll', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.category_doll')),
            ],
        ),
        migrations.CreateModel(
            name='Procurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('Quantity', models.IntegerField(default=0)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('Unit_price', models.IntegerField(null=True)),
                ('received_quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.category')),
            ],
        ),
        migrations.CreateModel(
            name='Sitterreg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sitter_name', models.CharField(blank='False', max_length=30, null='False')),
                ('Sitter_number', models.CharField(blank='False', max_length=30, null='False')),
                ('Date_of_birth', models.DateField(blank='True', null='True')),
                ('Contact', models.IntegerField()),
                ('Location', models.CharField(choices=[('kabalagala', 'kabalagala')], max_length=100)),
                ('Gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=100)),
                ('Level_of_education', models.CharField(choices=[('Degree', 'Degree'), ('Diploma', 'Diploma'), ('Certificate', 'Certificate')], default=0, max_length=200)),
                ('Next_of_kin', models.CharField(blank='False', max_length=30, null='False')),
                ('NIN', models.CharField(blank='False', max_length=30, null='False')),
                ('Recommenders_name', models.CharField(blank='False', max_length=30, null='False')),
                ('Religion', models.CharField(blank='True', max_length=30, null='True')),
            ],
        ),
        migrations.CreateModel(
            name='Used',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_issued', models.IntegerField(default=0)),
                ('issue_date', models.DateField(default=django.utils.timezone.now)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.procurement')),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('period', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.categorystay')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.babyreg')),
            ],
        ),
        migrations.CreateModel(
            name='Sitterpayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('babies_assigned', models.IntegerField(default=0)),
                ('sitter_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.sitterreg')),
            ],
        ),
        migrations.CreateModel(
            name='Sitter_arrival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sitter_number', models.IntegerField(default=0)),
                ('date_of_arrival', models.DateField(default=django.utils.timezone.now)),
                ('timein', models.TimeField()),
                ('Attendancestatus', models.CharField(choices=[('onduty', 'On Duty'), ('offduty', 'Off Duty')], max_length=100)),
                ('sitter_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.sitterreg')),
            ],
        ),
        migrations.CreateModel(
            name='Salesrecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_sold', models.IntegerField(default=0)),
                ('amount_received', models.IntegerField(default=0)),
                ('sale_date', models.DateField(default=django.utils.timezone.now)),
                ('unit_price', models.IntegerField(default=0)),
                ('doll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.doll')),
                ('payee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.babyreg')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payno', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('amount', models.IntegerField()),
                ('balance', models.IntegerField(blank=True, null=True)),
                ('c_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.categorystay')),
                ('payee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.babyreg')),
            ],
        ),
        migrations.CreateModel(
            name='Enrolledbabies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.sitterreg')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.babyreg')),
            ],
        ),
        migrations.CreateModel(
            name='Departure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('timeout', models.TimeField()),
                ('picker', models.CharField(max_length=200)),
                ('Contact', models.IntegerField()),
                ('NIN', models.CharField(blank='False', max_length=30, null='False')),
                ('comment', models.CharField(blank=True, max_length=200, null=True)),
                ('baby_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.babyreg')),
            ],
        ),
        migrations.AddField(
            model_name='babyreg',
            name='c_stay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.categorystay'),
        ),
    ]
