# Generated by Django 4.2.11 on 2024-04-23 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Babyreg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Baby_name', models.CharField(blank='False', max_length=30, null='False')),
                ('Baby_number', models.CharField(blank='False', max_length=30, null='False')),
                ('Date', models.DateTimeField(blank='False', max_length=30, null='False')),
                ('Gender', models.CharField(blank='False', max_length=30, null='False')),
                ('Age', models.IntegerField()),
                ('Location', models.CharField(blank='False', max_length=30, null='False')),
                ('Name_of_person_who_brought_the_baby', models.CharField(blank='False', max_length=30, null='False')),
                ('Name_of_the_person_that_has_taken_baby', models.CharField(blank='False', max_length=30, null='False')),
                ('Time_In', models.TimeField(blank='False', max_length=30, null='False')),
                ('Time_Out', models.TimeField(blank='False', max_length=30, null='False')),
                ('Parents_names', models.CharField(blank='False', max_length=30, null='False')),
                ('Comment', models.CharField(blank='False', max_length=100, null='False')),
            ],
        ),
        migrations.CreateModel(
            name='Categorymode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_mode', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categorypayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('p_mode', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categorystay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sitterreg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sitter_name', models.CharField(blank='False', max_length=30, null='False')),
                ('Sitter_number', models.CharField(blank='False', max_length=30, null='False')),
                ('Date_of_birth', models.DateTimeField(blank='True', null='True')),
                ('Contact', models.IntegerField()),
                ('Location', models.CharField(blank='False', max_length=30, null='False')),
                ('Gender', models.CharField(blank='False', max_length=10, null='False')),
                ('Level_of_education', models.CharField(blank='False', max_length=30, null='False')),
                ('Next_of_kin', models.CharField(blank='False', max_length=30, null='False')),
                ('NIN', models.CharField(blank='False', max_length=30, null='False')),
                ('Recommenders_name', models.CharField(blank='False', max_length=30, null='False')),
                ('Religion', models.CharField(blank='True', max_length=30, null='True')),
            ],
        ),
        migrations.CreateModel(
            name='Doll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doll_name', models.CharField(blank='False', max_length=100, null='False')),
                ('number', models.IntegerField(blank='False', max_length=100, null='False')),
                ('price', models.IntegerField(blank='False', max_length=100, null='False')),
                ('baby_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.babyreg')),
            ],
        ),
        migrations.AddField(
            model_name='babyreg',
            name='assign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.sitterreg'),
        ),
        migrations.AddField(
            model_name='babyreg',
            name='c_stay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.categorystay'),
        ),
    ]
