# Generated by Django 4.2.11 on 2024-05-08 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='babyreg',
            name='Baby_number',
        ),
    ]
