# Generated by Django 4.2.11 on 2024-04-29 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doll',
            old_name='color',
            new_name='doll_number',
        ),
        migrations.RemoveField(
            model_name='babyreg',
            name='Comment',
        ),
        migrations.RemoveField(
            model_name='babyreg',
            name='Name_of_person_who_brought_the_baby',
        ),
        migrations.RemoveField(
            model_name='babyreg',
            name='Name_of_the_person_that_has_taken_baby',
        ),
        migrations.RemoveField(
            model_name='babyreg',
            name='Time_In',
        ),
        migrations.RemoveField(
            model_name='babyreg',
            name='Time_Out',
        ),
        migrations.RemoveField(
            model_name='doll',
            name='size',
        ),
    ]
