# Generated by Django 4.2.11 on 2024-05-18 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procurement',
            name='Unit_price',
        ),
        migrations.AlterField(
            model_name='sitterreg',
            name='Gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=100),
        ),
    ]
