# Generated by Django 4.2.11 on 2024-04-23 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doll',
            name='number',
            field=models.IntegerField(blank='False', null='False'),
        ),
        migrations.AlterField(
            model_name='doll',
            name='price',
            field=models.IntegerField(blank='False', null='False'),
        ),
    ]
