# Generated by Django 4.2.11 on 2024-05-02 11:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_payment_currency_payment_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitterreg',
            name='Gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=100),
        ),
        migrations.AlterField(
            model_name='sitterreg',
            name='Level_of_education',
            field=models.CharField(choices=[('Degree', 'Degree'), ('Diploma', 'Diploma'), ('Certificate', 'Certificate')], default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='sitterreg',
            name='Location',
            field=models.CharField(choices=[('kabalagala', 'kabalagala')], max_length=100),
        ),
        migrations.CreateModel(
            name='Sitterpayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('numbers_of_babies_attended_to', models.IntegerField(default=0)),
                ('sitter_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.sitterreg')),
            ],
        ),
        migrations.CreateModel(
            name='Sitter_arrival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sitter_number', models.IntegerField(default=0)),
                ('date_of_arrival', models.DateField(default=django.utils.timezone.now)),
                ('timein', models.TimeField()),
                ('Attendancestatus', models.CharField(choices=[('onduty', 'onduty')], max_length=100)),
                ('sitter_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.sitterreg')),
            ],
        ),
        migrations.CreateModel(
            name='assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('day', models.CharField(choices=[('fullday', 'fullday'), ('halfday', 'halfday')], max_length=100)),
                ('baby_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.babyreg')),
                ('sitter_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.sitterreg')),
            ],
        ),
    ]
