# Generated by Django 4.2.11 on 2024-04-29 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_color_doll_doll_number_remove_babyreg_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='babyreg',
            name='c_stay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.categorystay'),
        ),
    ]
