# Generated by Django 4.2.11 on 2024-05-08 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_babyreg_baby_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='babyreg',
            name='assigned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.sitter_arrival'),
        ),
    ]
