# Generated by Django 4.2.11 on 2024-05-06 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_babyreg_timein'),
    ]

    operations = [
        migrations.AddField(
            model_name='babyreg',
            name='timein',
            field=models.TimeField(default='9:00 AM'),
            preserve_default=False,
        ),
    ]
