# Generated by Django 4.2.11 on 2024-04-23 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_doll_number_alter_doll_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_no', models.IntegerField(blank=True, null=True)),
                ('Amount', models.IntegerField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, default='Ugx', max_length=5, null=True)),
                ('c_pay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.categorystay')),
                ('payee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.babyreg')),
            ],
        ),
        migrations.DeleteModel(
            name='Categorymode',
        ),
        migrations.DeleteModel(
            name='Categorypayment',
        ),
    ]
