# Generated by Django 4.2.11 on 2024-05-18 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_procurement_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doll',
            name='Unit_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='doll',
            name='received_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
