# Generated by Django 4.2.11 on 2024-05-02 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_sitterreg_gender_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arrival',
            old_name='care_giver',
            new_name='broughtby',
        ),
    ]
