# Generated by Django 4.2.11 on 2024-05-06 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_babyreg_timein'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='babyreg',
            name='timein',
        ),
    ]
