# Generated by Django 4.2.11 on 2024-04-29 14:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_babyreg_c_stay'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baby_number', models.IntegerField(default=0)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('timeout', models.TimeField()),
                ('picker', models.CharField(max_length=200)),
                ('comment', models.CharField(blank=True, max_length=200, null=True)),
                ('baby_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.babyreg')),
            ],
        ),
        migrations.CreateModel(
            name='Arrival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baby_number', models.IntegerField(default=0)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('timein', models.TimeField()),
                ('care_giver', models.CharField(max_length=200)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('baby_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.babyreg')),
            ],
        ),
    ]
