# Generated by Django 4.2.11 on 2024-04-23 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_payment_delete_categorymode_delete_categorypayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='babyreg',
            name='Date',
            field=models.DateField(blank='False', max_length=30, null='False'),
        ),
    ]
