# Generated by Django 4.2.11 on 2024-05-08 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_babyreg_assigned'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorymode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payno',
        ),
        migrations.AddField(
            model_name='payment',
            name='c_mode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.categorymode'),
        ),
    ]
