# Generated by Django 4.2.11 on 2024-05-06 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_babyreg_timein'),
    ]

    operations = [
        migrations.AddField(
            model_name='babyreg',
            name='timein',
            field=models.TimeField(default=1),
            preserve_default=False,
        ),
    ]
