# Generated by Django 4.2.11 on 2024-05-18 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_doll_unit_price_alter_doll_received_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procurement',
            name='Quantity',
            field=models.IntegerField(default=0),
        ),
    ]
