# Generated by Django 4.2.11 on 2024-04-23 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_babyreg_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitterreg',
            name='Date_of_birth',
            field=models.DateField(blank='True', null='True'),
        ),
    ]
