# Generated by Django 4.2.11 on 2024-05-08 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_categorymode_remove_payment_payno_payment_c_mode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='amount',
            new_name='amount_paid',
        ),
        migrations.AddField(
            model_name='payment',
            name='selected_amount',
            field=models.IntegerField(choices=[(10000, '10,000'), (15000, '15,000'), (30000, '30,000'), (45000, '45,000')], default=0),
        ),
    ]
