# Generated by Django 4.2.11 on 2024-05-03 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_care_giver_arrival_broughtby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitter_arrival',
            name='Attendancestatus',
            field=models.CharField(choices=[('onduty', 'On Duty'), ('offduty', 'Off Duty')], max_length=100),
        ),
    ]
