# Generated by Django 4.2.11 on 2024-05-03 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_sitter_arrival_attendancestatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='amount',
        ),
        migrations.DeleteModel(
            name='assignment',
        ),
    ]
