# Generated by Django 4.2.11 on 2024-05-08 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_amount_payment_amount_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='selected_amount',
            field=models.IntegerField(choices=[(10000, '10,000'), (15000, '15,000'), (30000, '300,000'), (45000, '450,000')], default=0),
        ),
    ]
