# Generated by Django 4.2.11 on 2024-05-18 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_procurement_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='babyreg',
            name='Age',
            field=models.CharField(max_length=20),
        ),
    ]
