# Generated by Django 4.2.11 on 2024-05-06 05:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_babyreg_timein'),
    ]

    operations = [
        migrations.AddField(
            model_name='babyreg',
            name='timein',
            field=models.TimeField(default=datetime.datetime(2024, 5, 6, 5, 28, 29, 952462, tzinfo=datetime.timezone.utc)),
        ),
    ]
