# Generated by Django 4.2.11 on 2024-05-08 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_payment_selected_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('cleared', 'cleared'), ('pending', 'pending')], default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='selected_amount',
            field=models.IntegerField(choices=[(10000, '10,000'), (15000, '15,000'), (300000, '300,000'), (450000, '450,000')], default=0),
        ),
    ]
