# Generated by Django 4.2.11 on 2024-04-30 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_category_procurement_usedlog_delete_payment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usedlog',
            new_name='Used',
        ),
    ]
