# Generated by Django 4.2.11 on 2024-04-25 10:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_category_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_sale', models.DateField(default=django.utils.timezone.now)),
                ('contact', models.CharField(max_length=50)),
                ('quantity', models.IntegerField(default=0)),
                ('amount_received', models.IntegerField(default=0)),
                ('issued_to', models.CharField(max_length=100)),
                ('unit_price', models.IntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.product')),
            ],
        ),
    ]
