# Generated by Django 4.2.11 on 2024-05-03 19:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_payment_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='babyreg',
            name='Date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
