# Generated by Django 4.2.11 on 2024-05-18 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_salesrecord_doll_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesrecord',
            old_name='doll_number',
            new_name='doll_no',
        ),
    ]
