# Generated by Django 4.2.11 on 2024-05-06 05:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_babyreg_timein'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departure',
            old_name='Contact',
            new_name='contact',
        ),
        migrations.AlterField(
            model_name='babyreg',
            name='timein',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
