# Generated by Django 4.2.11 on 2024-05-08 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_payment_payment_status_alter_payment_selected_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('Cleared', 'Cleared'), ('Pending', 'Pending')], default=0, max_length=100),
        ),
    ]
