# Generated by Django 4.2.11 on 2024-04-28 13:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_doll_baby_name_remove_doll_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doll',
            name='doll_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='doll',
            name='doll_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='doll',
            name='issued_quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='doll',
            name='received_quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='doll',
            name='total_quantity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='doll',
            name='unit_price',
            field=models.IntegerField(),
        ),
    ]
