# Generated by Django 4.2.11 on 2024-05-01 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='Date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.CharField(blank=True, default='Ugx', max_length=10, null=True),
        ),
    ]
