# Generated by Django 4.2.11 on 2024-05-06 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_rename_contact_departure_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departure',
            name='contact',
            field=models.CharField(max_length=30),
        ),
    ]
