# Generated by Django 4.2.11 on 2024-05-18 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_rename_doll_number_salesrecord_doll_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitter_departure',
            name='comment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
