# Generated by Django 4.2.11 on 2024-05-03 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_babyreg_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arrival',
            name='amount',
        ),
    ]
