# Generated by Django 4.2.11 on 2024-05-08 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_payment_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='used',
            name='issued_to',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
