# Generated by Django 4.2.11 on 2024-05-03 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_arrival_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitterpayment',
            old_name='numbers_of_babies_attended_to',
            new_name='babies_assigned',
        ),
    ]
