# Generated by Django 4.2.11 on 2024-05-08 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_used_issued_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitterpayment',
            name='amount',
        ),
    ]
