# Generated by Django 4.2.11 on 2024-05-19 12:57

import datetime
from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_sitter_departure_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitterreg',
            name='Date_of_birth',
            field=models.DateField(default=datetime.datetime(2024, 5, 19, 12, 57, 18, 671129, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='sitterreg',
            name='Sitter_name',
            field=models.CharField(max_length=30, validators=[home.models.validate_letters]),
        ),
    ]
