# Generated by Django 4.2.11 on 2024-05-06 07:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_departure_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitter_arrival',
            name='timeout',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
