# Generated by Django 4.2.11 on 2024-05-19 13:05

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_sitterreg_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitterreg',
            name='Date_of_birth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='sitterreg',
            name='NIN',
            field=models.CharField(max_length=30, validators=[home.models.validate_NIN_length]),
        ),
        migrations.AlterField(
            model_name='sitterreg',
            name='Sitter_number',
            field=models.CharField(max_length=30, validators=[home.models.validate_numbers]),
        ),
    ]
