# Generated by Django 4.2.11 on 2024-05-06 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_sitter_arrival_timeout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitter_arrival',
            name='timeout',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
