# Generated by Django 4.2.11 on 2024-05-08 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_sitterpayment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitterpayment',
            name='amount',
            field=models.IntegerField(default=3000),
        ),
    ]
