# Generated by Django 4.2.11 on 2024-05-03 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_rename_numbers_of_babies_attended_to_sitterpayment_babies_assigned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitterpayment',
            name='amount',
            field=models.IntegerField(choices=[('Ugx 3000', 'Ugx 3000')]),
        ),
    ]
