# Generated by Django 4.2.11 on 2024-05-19 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_sitterreg_date_of_birth_alter_sitterreg_nin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitterreg',
            name='Date_of_birth',
            field=models.DateField(null=True),
        ),
    ]
