# Generated by Django 4.2.11 on 2024-05-06 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_sitter_arrival_timeout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitter_arrival',
            name='sitter_number',
        ),
    ]
