# Generated by Django 4.2.11 on 2024-05-09 07:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_sitterpayment_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='babyreg',
            name='timein',
        ),
        migrations.AddField(
            model_name='babyreg',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='sitterreg',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='babyreg',
            name='Date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
