# Generated by Django 4.2.11 on 2024-05-03 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_sitterpayment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitterpayment',
            name='sitter_number',
            field=models.CharField(blank='False', max_length=30, null='False'),
            preserve_default='False',
        ),
        migrations.AlterField(
            model_name='arrival',
            name='baby_number',
            field=models.CharField(blank='False', max_length=30, null='False'),
        ),
        migrations.AlterField(
            model_name='departure',
            name='baby_number',
            field=models.CharField(blank='False', max_length=30, null='False'),
        ),
        migrations.AlterField(
            model_name='sitterpayment',
            name='amount',
            field=models.CharField(choices=[('Ugx 3000', 'Ugx 3000')], max_length=30),
        ),
    ]
