# Generated by Django 4.2.11 on 2024-05-06 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_remove_sitter_arrival_sitter_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitterpayment',
            name='sitter_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.sitter_arrival'),
        ),
    ]
