# Generated by Django 4.2.11 on 2024-05-06 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_sitterpayment_sitter_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='period',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='student',
        ),
        migrations.DeleteModel(
            name='Enrolledbabies',
        ),
        migrations.DeleteModel(
            name='Transactions',
        ),
    ]
