# Generated by Django 4.2.11 on 2024-05-11 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_babyreg_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='babyreg',
            name='fathers_names',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='babyreg',
            name='mothers_names',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
