# Generated by Django 4.2.11 on 2024-05-03 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_sitterpayment_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitterpayment',
            name='sitter_number',
        ),
        migrations.AlterField(
            model_name='departure',
            name='baby_number',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
