# Generated by Django 4.2.11 on 2024-05-19 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_assign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assign',
            name='no_of_babies_attended',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.babyreg'),
        ),
        migrations.AlterField(
            model_name='assign',
            name='siter_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.sitter_arrival'),
        ),
    ]
