# Generated by Django 4.2.11 on 2024-05-03 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_remove_sitterpayment_sitter_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitterpayment',
            name='amount',
            field=models.IntegerField(default=0, max_length=30),
        ),
    ]
