# Generated by Django 4.2.11 on 2024-05-11 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_babyreg_fathers_names_babyreg_mothers_names'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='babyreg',
            name='Parents_names',
        ),
    ]
