# Generated by Django 4.2.11 on 2024-05-11 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_remove_babyreg_parents_names'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='babyreg',
            name='assigned',
        ),
        migrations.RemoveField(
            model_name='sitterpayment',
            name='sitter_names',
        ),
        migrations.AddField(
            model_name='sitter_arrival',
            name='babies',
            field=models.ManyToManyField(to='home.babyreg'),
        ),
        migrations.AlterField(
            model_name='sitter_arrival',
            name='Attendancestatus',
            field=models.BooleanField(default=False),
        ),
    ]
