# Generated by Django 4.2.11 on 2024-05-19 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_assign_no_of_babies_attended_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitter_arrival',
            name='num_babies',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sitter_arrival',
            name='payment',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.DeleteModel(
            name='Assign',
        ),
    ]
