# Generated by Django 4.2.11 on 2024-05-03 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_sitterpayment_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='babyreg',
            name='assign',
        ),
        migrations.AddField(
            model_name='arrival',
            name='assign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.sitterreg'),
        ),
    ]
