# Generated by Django 4.2.11 on 2024-05-03 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_remove_babyreg_assign_arrival_assign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitterpayment',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
