# Generated by Django 4.2.11 on 2024-05-11 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_remove_babyreg_assigned_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitter_arrival',
            name='timein',
        ),
        migrations.RemoveField(
            model_name='sitter_arrival',
            name='timeout',
        ),
    ]
