# Generated by Django 4.2.11 on 2024-05-20 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_departure_nin_alter_departure_contact_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='babyreg',
            old_name='brought',
            new_name='brought_by',
        ),
    ]
