# Generated by Django 4.2.11 on 2024-05-12 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_remove_sitter_arrival_timein_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitterreg',
            name='Sitter_number',
        ),
    ]
