# Generated by Django 4.2.11 on 2024-05-12 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_remove_sitterreg_sitter_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitterreg',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='sitterreg',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
