# Generated by Django 4.2.11 on 2024-05-12 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_sitterreg_created_at_alter_sitterreg_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitter_arrival',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='sitter_arrival',
            name='date_of_arrival',
            field=models.DateTimeField(),
        ),
    ]
