# Generated by Django 4.2.11 on 2024-05-21 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_alter_sitterreg_sitter_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='babyreg',
            name='baby_number',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
