# Generated by Django 4.2.11 on 2024-05-12 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_sitter_arrival_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitterreg',
            name='Contact',
            field=models.CharField(max_length=30),
        ),
    ]
