# Generated by Django 4.2.11 on 2024-05-12 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_sitterreg_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='departure',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='departure',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
