# Generated by Django 4.2.11 on 2024-05-12 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_departure_created_at_alter_departure_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departure',
            name='timeout',
        ),
    ]
