# Generated by Django 4.2.11 on 2024-05-13 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_remove_departure_timeout'),
    ]

    operations = [
        migrations.AddField(
            model_name='babyreg',
            name='baby_number',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitterreg',
            name='Sitter_number',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
