# Generated by Django 4.2.11 on 2024-05-13 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_babyreg_baby_number_sitterreg_sitter_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitterreg',
            name='Religion',
            field=models.CharField(choices=[('Anglican', 'Anglican'), ('Catholic', 'Catholic'), ('Pentecostal', 'Pentecostal'), ('Muslim', 'Muslim'), ('Other', 'Other')], max_length=100),
        ),
    ]
