# Generated by Django 4.2.11 on 2024-05-13 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_alter_sitterreg_religion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitterreg',
            name='Location',
            field=models.CharField(choices=[('Kabalagala', 'Kabalagala')], max_length=100),
        ),
    ]
