# Generated by Django 4.2.11 on 2024-05-14 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_alter_sitterreg_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sitter_departure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sitter_number', models.CharField(max_length=30, null=True)),
                ('departure_time', models.DateTimeField()),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('sitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.sitterreg')),
            ],
        ),
    ]
